"""init

Revision ID: 1374ac1ba77b
Revises: 
Create Date: 2026-01-20 09:40:25.266503

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1374ac1ba77b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets_certificate',
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID主键'),
    sa.Column('external_id', sa.String(length=255), nullable=False, comment='业务唯一标识（建议使用 cert:SHA256）'),
    sa.Column('subject_cn', sa.String(length=255), nullable=True, comment='主题通用名称（Subject Common Name）'),
    sa.Column('issuer_cn', sa.String(length=255), nullable=True, comment='颁发者通用名称（Issuer Common Name）'),
    sa.Column('issuer_org', sa.String(length=255), nullable=True, comment='颁发者组织名称'),
    sa.Column('valid_from', sa.BigInteger(), nullable=True, comment='生效时间戳（Unix秒）'),
    sa.Column('valid_to', sa.BigInteger(), nullable=True, comment='过期时间戳（Unix秒）'),
    sa.Column('days_to_expire', sa.Integer(), nullable=True, comment='剩余有效天数（可为负数表示已过期）'),
    sa.Column('is_expired', sa.Boolean(), nullable=False, comment='是否已过期'),
    sa.Column('is_self_signed', sa.Boolean(), nullable=False, comment='是否为自签名证书'),
    sa.Column('is_revoked', sa.Boolean(), nullable=False, comment='是否已被吊销'),
    sa.Column('san_count', sa.Integer(), nullable=False, comment='SAN（主题备用名称）数量'),
    sa.Column('scope_policy', sa.String(length=50), nullable=False, comment='范围策略（IN_SCOPE/OUT_OF_SCOPE）'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='元数据（JSONB格式，包含subject_alt_names、fingerprints等）'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间戳'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间戳'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间戳'),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='创建者标识'),
    sa.CheckConstraint('san_count >= 0', name=op.f('ck_assets_certificate_chk_cert_san_count')),
    sa.CheckConstraint('valid_from IS NULL OR valid_to IS NULL OR valid_from <= valid_to', name=op.f('ck_assets_certificate_chk_cert_valid_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets_certificate')),
    comment='证书资产表'
    )
    op.create_index(op.f('ix_assets_certificate_created_at'), 'assets_certificate', ['created_at'], unique=False)
    op.create_index(op.f('ix_assets_certificate_external_id'), 'assets_certificate', ['external_id'], unique=True)
    op.create_index(op.f('ix_assets_certificate_is_deleted'), 'assets_certificate', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_assets_certificate_is_expired'), 'assets_certificate', ['is_expired'], unique=False)
    op.create_index(op.f('ix_assets_certificate_is_revoked'), 'assets_certificate', ['is_revoked'], unique=False)
    op.create_index(op.f('ix_assets_certificate_is_self_signed'), 'assets_certificate', ['is_self_signed'], unique=False)
    op.create_index(op.f('ix_assets_certificate_issuer_cn'), 'assets_certificate', ['issuer_cn'], unique=False)
    op.create_index(op.f('ix_assets_certificate_scope_policy'), 'assets_certificate', ['scope_policy'], unique=False)
    op.create_index(op.f('ix_assets_certificate_subject_cn'), 'assets_certificate', ['subject_cn'], unique=False)
    op.create_table('assets_client_application',
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID主键'),
    sa.Column('external_id', sa.String(length=255), nullable=False, comment='业务唯一标识（建议使用 app:PLATFORM:PACKAGE_NAME）'),
    sa.Column('app_name', sa.String(length=255), nullable=False, comment='应用名称'),
    sa.Column('package_name', sa.String(length=255), nullable=False, comment='包名/应用标识符（如 com.example.app）'),
    sa.Column('version', sa.String(length=100), nullable=True, comment='版本号'),
    sa.Column('platform', sa.String(length=50), nullable=False, comment='平台类型（Android/iOS/Windows/macOS/Linux）'),
    sa.Column('bundle_id', sa.String(length=255), nullable=True, comment='Bundle标识符（iOS专用）'),
    sa.Column('risk_score', sa.Float(), nullable=False, comment='风险评分（0-10）'),
    sa.Column('scope_policy', sa.String(length=50), nullable=False, comment='范围策略（IN_SCOPE/OUT_OF_SCOPE）'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='元数据（JSONB格式，包含permissions、signatures等）'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间戳'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间戳'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间戳'),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='创建者标识'),
    sa.CheckConstraint("platform IN ('Android', 'iOS', 'Windows', 'macOS', 'Linux')", name=op.f('ck_assets_client_application_chk_app_platform')),
    sa.CheckConstraint('risk_score >= 0 AND risk_score <= 10', name=op.f('ck_assets_client_application_chk_app_risk_score')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets_client_application')),
    comment='客户端应用资产表'
    )
    op.create_index(op.f('ix_assets_client_application_app_name'), 'assets_client_application', ['app_name'], unique=False)
    op.create_index(op.f('ix_assets_client_application_created_at'), 'assets_client_application', ['created_at'], unique=False)
    op.create_index(op.f('ix_assets_client_application_external_id'), 'assets_client_application', ['external_id'], unique=True)
    op.create_index(op.f('ix_assets_client_application_is_deleted'), 'assets_client_application', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_assets_client_application_package_name'), 'assets_client_application', ['package_name'], unique=False)
    op.create_index(op.f('ix_assets_client_application_platform'), 'assets_client_application', ['platform'], unique=False)
    op.create_index(op.f('ix_assets_client_application_scope_policy'), 'assets_client_application', ['scope_policy'], unique=False)
    op.create_table('assets_credential',
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID主键'),
    sa.Column('external_id', sa.String(length=255), nullable=False, comment='业务唯一标识（建议使用 cred:TYPE:HASH）'),
    sa.Column('cred_type', sa.String(length=50), nullable=False, comment='凭证类型（PASSWORD/API_KEY/TOKEN/SSH_KEY/CERTIFICATE等）'),
    sa.Column('provider', sa.String(length=255), nullable=True, comment='提供方/来源（如 GitHub、AWS、Google）'),
    sa.Column('username', sa.String(length=255), nullable=True, comment='用户名'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='电子邮箱'),
    sa.Column('phone', sa.String(length=50), nullable=True, comment='电话号码'),
    sa.Column('leaked_count', sa.Integer(), nullable=False, comment='泄露次数'),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='凭证内容（JSONB格式，包含password_hash、api_key等敏感信息）'),
    sa.Column('validation_result', sa.String(length=50), nullable=True, comment='验证结果（VALID/INVALID/UNKNOWN）'),
    sa.Column('scope_policy', sa.String(length=50), nullable=False, comment='范围策略（IN_SCOPE/OUT_OF_SCOPE）'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='元数据（JSONB格式，包含source、breach_date等）'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间戳'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间戳'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间戳'),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='创建者标识'),
    sa.CheckConstraint("validation_result IS NULL OR validation_result IN ('VALID', 'INVALID', 'UNKNOWN')", name=op.f('ck_assets_credential_chk_cred_validation_result')),
    sa.CheckConstraint('leaked_count >= 0', name=op.f('ck_assets_credential_chk_cred_leaked_count')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets_credential')),
    comment='凭证资产表'
    )
    op.create_index(op.f('ix_assets_credential_created_at'), 'assets_credential', ['created_at'], unique=False)
    op.create_index(op.f('ix_assets_credential_cred_type'), 'assets_credential', ['cred_type'], unique=False)
    op.create_index(op.f('ix_assets_credential_email'), 'assets_credential', ['email'], unique=False)
    op.create_index(op.f('ix_assets_credential_external_id'), 'assets_credential', ['external_id'], unique=True)
    op.create_index(op.f('ix_assets_credential_is_deleted'), 'assets_credential', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_assets_credential_provider'), 'assets_credential', ['provider'], unique=False)
    op.create_index(op.f('ix_assets_credential_scope_policy'), 'assets_credential', ['scope_policy'], unique=False)
    op.create_index(op.f('ix_assets_credential_username'), 'assets_credential', ['username'], unique=False)
    op.create_index(op.f('ix_assets_credential_validation_result'), 'assets_credential', ['validation_result'], unique=False)
    op.create_table('assets_domain',
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID主键'),
    sa.Column('external_id', sa.String(length=255), nullable=False, comment='业务唯一标识（与Neo4j节点id对齐）'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='完整域名'),
    sa.Column('root_domain', sa.String(length=255), nullable=True, comment='根域名（用于聚合）'),
    sa.Column('tier', sa.Integer(), nullable=False, comment='层级深度'),
    sa.Column('is_resolved', sa.Boolean(), nullable=False, comment='是否能解析'),
    sa.Column('is_wildcard', sa.Boolean(), nullable=False, comment='是否为泛解析'),
    sa.Column('is_internal', sa.Boolean(), nullable=False, comment='是否解析到内网'),
    sa.Column('has_waf', sa.Boolean(), nullable=False, comment='是否有WAF'),
    sa.Column('scope_policy', sa.String(length=50), nullable=False, comment='范围策略'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='元数据（DNS记录、ICP备案、技术栈等）'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='创建者'),
    sa.CheckConstraint('tier >= 1', name=op.f('ck_assets_domain_chk_domain_tier')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets_domain')),
    comment='域名表'
    )
    op.create_index(op.f('ix_assets_domain_created_at'), 'assets_domain', ['created_at'], unique=False)
    op.create_index(op.f('ix_assets_domain_external_id'), 'assets_domain', ['external_id'], unique=True)
    op.create_index(op.f('ix_assets_domain_is_deleted'), 'assets_domain', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_assets_domain_is_resolved'), 'assets_domain', ['is_resolved'], unique=False)
    op.create_index(op.f('ix_assets_domain_name'), 'assets_domain', ['name'], unique=True)
    op.create_index(op.f('ix_assets_domain_root_domain'), 'assets_domain', ['root_domain'], unique=False)
    op.create_index(op.f('ix_assets_domain_scope_policy'), 'assets_domain', ['scope_policy'], unique=False)
    op.create_table('assets_ip',
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID主键'),
    sa.Column('external_id', sa.String(length=255), nullable=False, comment='业务唯一标识（与Neo4j节点id对齐）'),
    sa.Column('address', postgresql.INET(), nullable=False, comment='IP地址'),
    sa.Column('version', sa.Integer(), nullable=False, comment='IP版本（4或6）'),
    sa.Column('is_cloud', sa.Boolean(), nullable=False, comment='是否为云主机'),
    sa.Column('is_internal', sa.Boolean(), nullable=False, comment='是否为内网IP'),
    sa.Column('is_cdn', sa.Boolean(), nullable=False, comment='是否为CDN节点'),
    sa.Column('open_ports_count', sa.Integer(), nullable=False, comment='开放端口总数'),
    sa.Column('risk_score', sa.Numeric(precision=3, scale=1), nullable=False, comment='聚合风险值'),
    sa.Column('vuln_critical_count', sa.Integer(), nullable=False, comment='严重漏洞数量'),
    sa.Column('country_code', sa.String(length=2), nullable=True, comment='国家代码'),
    sa.Column('asn_number', sa.String(length=20), nullable=True, comment='AS号'),
    sa.Column('scope_policy', sa.String(length=50), nullable=False, comment='范围策略'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='元数据（OS指纹、地理位置、云元数据等）'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='创建者'),
    sa.CheckConstraint('open_ports_count >= 0', name=op.f('ck_assets_ip_chk_ip_open_ports_count')),
    sa.CheckConstraint('risk_score >= 0 AND risk_score <= 10', name=op.f('ck_assets_ip_chk_ip_risk_score')),
    sa.CheckConstraint('version IN (4, 6)', name=op.f('ck_assets_ip_chk_ip_version')),
    sa.CheckConstraint('vuln_critical_count >= 0', name=op.f('ck_assets_ip_chk_ip_vuln_critical_count')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets_ip')),
    sa.UniqueConstraint('address', name=op.f('uq_assets_ip_address')),
    comment='IP/主机表'
    )
    op.create_index(op.f('ix_assets_ip_asn_number'), 'assets_ip', ['asn_number'], unique=False)
    op.create_index(op.f('ix_assets_ip_country_code'), 'assets_ip', ['country_code'], unique=False)
    op.create_index(op.f('ix_assets_ip_created_at'), 'assets_ip', ['created_at'], unique=False)
    op.create_index(op.f('ix_assets_ip_external_id'), 'assets_ip', ['external_id'], unique=True)
    op.create_index(op.f('ix_assets_ip_is_cloud'), 'assets_ip', ['is_cloud'], unique=False)
    op.create_index(op.f('ix_assets_ip_is_deleted'), 'assets_ip', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_assets_ip_scope_policy'), 'assets_ip', ['scope_policy'], unique=False)
    op.create_index(op.f('ix_assets_ip_version'), 'assets_ip', ['version'], unique=False)
    op.create_table('assets_netblock',
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID主键'),
    sa.Column('external_id', sa.String(length=255), nullable=False, comment='业务唯一标识（与Neo4j节点id对齐）'),
    sa.Column('cidr', postgresql.CIDR(), nullable=False, comment='网段CIDR表示（如 192.168.0.0/24）'),
    sa.Column('asn_number', sa.String(length=20), nullable=True, comment='AS自治系统号（如 AS37963）'),
    sa.Column('capacity', sa.BigInteger(), nullable=True, comment='网段可容纳的IP地址数量（自动从CIDR计算）'),
    sa.Column('live_count', sa.Integer(), nullable=False, comment='存活的IP数量'),
    sa.Column('risk_score', sa.Numeric(precision=3, scale=1), nullable=False, comment='风险评分（0.0-10.0）'),
    sa.Column('scope_policy', sa.String(length=50), nullable=False, comment='范围策略（IN_SCOPE/OUT_OF_SCOPE）'),
    sa.Column('is_internal', sa.Boolean(), nullable=False, comment='是否为内网段（RFC1918私有地址）'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='元数据（JSONB格式，包含net_name、description等）'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间戳'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间戳'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间戳'),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='创建者标识'),
    sa.CheckConstraint('capacity IS NULL OR capacity >= 0', name=op.f('ck_assets_netblock_chk_netblock_capacity')),
    sa.CheckConstraint('capacity IS NULL OR live_count <= capacity', name=op.f('ck_assets_netblock_chk_netblock_live_count_capacity')),
    sa.CheckConstraint('live_count >= 0', name=op.f('ck_assets_netblock_chk_netblock_live_count')),
    sa.CheckConstraint('risk_score >= 0 AND risk_score <= 10', name=op.f('ck_assets_netblock_chk_netblock_risk_score')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets_netblock')),
    comment='网段资产表'
    )
    op.create_index(op.f('ix_assets_netblock_asn_number'), 'assets_netblock', ['asn_number'], unique=False)
    op.create_index(op.f('ix_assets_netblock_cidr'), 'assets_netblock', ['cidr'], unique=True)
    op.create_index(op.f('ix_assets_netblock_created_at'), 'assets_netblock', ['created_at'], unique=False)
    op.create_index(op.f('ix_assets_netblock_external_id'), 'assets_netblock', ['external_id'], unique=True)
    op.create_index(op.f('ix_assets_netblock_is_deleted'), 'assets_netblock', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_assets_netblock_is_internal'), 'assets_netblock', ['is_internal'], unique=False)
    op.create_index(op.f('ix_assets_netblock_scope_policy'), 'assets_netblock', ['scope_policy'], unique=False)
    op.create_table('assets_organization',
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID主键'),
    sa.Column('external_id', sa.String(length=255), nullable=False, comment='业务唯一标识（与Neo4j节点id对齐）'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='简短名称'),
    sa.Column('full_name', sa.String(length=500), nullable=True, comment='完整注册名称'),
    sa.Column('credit_code', sa.String(length=100), nullable=True, comment='统一社会信用代码'),
    sa.Column('is_primary', sa.Boolean(), nullable=False, comment='是否为一级目标'),
    sa.Column('tier', sa.Integer(), nullable=False, comment='层级：0=总部, 1=子公司'),
    sa.Column('asset_count', sa.Integer(), nullable=False, comment='资产总数（聚合字段）'),
    sa.Column('risk_score', sa.Numeric(precision=3, scale=1), nullable=False, comment='风险评分 0-10'),
    sa.Column('scope_policy', sa.String(length=50), nullable=False, comment='范围策略：IN_SCOPE, OUT_OF_SCOPE'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='元数据（JSONB）'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='创建者'),
    sa.CheckConstraint('asset_count >= 0', name=op.f('ck_assets_organization_chk_org_asset_count')),
    sa.CheckConstraint('risk_score >= 0 AND risk_score <= 10', name=op.f('ck_assets_organization_chk_org_risk_score')),
    sa.CheckConstraint('tier >= 0', name=op.f('ck_assets_organization_chk_org_tier')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets_organization')),
    comment='组织/公司表'
    )
    op.create_index(op.f('ix_assets_organization_created_at'), 'assets_organization', ['created_at'], unique=False)
    op.create_index(op.f('ix_assets_organization_credit_code'), 'assets_organization', ['credit_code'], unique=True)
    op.create_index(op.f('ix_assets_organization_external_id'), 'assets_organization', ['external_id'], unique=True)
    op.create_index(op.f('ix_assets_organization_is_deleted'), 'assets_organization', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_assets_organization_is_primary'), 'assets_organization', ['is_primary'], unique=False)
    op.create_index(op.f('ix_assets_organization_name'), 'assets_organization', ['name'], unique=False)
    op.create_index(op.f('ix_assets_organization_scope_policy'), 'assets_organization', ['scope_policy'], unique=False)
    op.create_table('assets_relationship',
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID primary key'),
    sa.Column('source_external_id', sa.String(length=255), nullable=False, comment='Source node external id'),
    sa.Column('source_type', sa.String(length=50), nullable=False, comment='Source node type (e.g., Organization, Domain, IP)'),
    sa.Column('target_external_id', sa.String(length=255), nullable=False, comment='Target node external id'),
    sa.Column('target_type', sa.String(length=50), nullable=False, comment='Target node type (e.g., Organization, Domain, IP)'),
    sa.Column('relation_type', sa.String(length=50), nullable=False, comment='Relationship type (e.g., OWNS_DOMAIN, RESOLVES_TO)'),
    sa.Column('edge_key', sa.String(length=255), nullable=False, comment='Disambiguation key for multiple edges of same type'),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Relationship properties (e.g., percent, record_type, first_seen)'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Deletion timestamp'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp'),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='Creator identifier'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets_relationship')),
    sa.UniqueConstraint('source_external_id', 'source_type', 'target_external_id', 'target_type', 'relation_type', 'edge_key', name='uq_assets_relationship_key'),
    comment='Asset relationships (edges in the graph)'
    )
    op.create_index(op.f('ix_assets_relationship_created_at'), 'assets_relationship', ['created_at'], unique=False)
    op.create_index(op.f('ix_assets_relationship_is_deleted'), 'assets_relationship', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_assets_relationship_relation_type'), 'assets_relationship', ['relation_type'], unique=False)
    op.create_index(op.f('ix_assets_relationship_source_external_id'), 'assets_relationship', ['source_external_id'], unique=False)
    op.create_index(op.f('ix_assets_relationship_source_type'), 'assets_relationship', ['source_type'], unique=False)
    op.create_index(op.f('ix_assets_relationship_target_external_id'), 'assets_relationship', ['target_external_id'], unique=False)
    op.create_index(op.f('ix_assets_relationship_target_type'), 'assets_relationship', ['target_type'], unique=False)
    op.create_table('assets_service',
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID主键'),
    sa.Column('external_id', sa.String(length=255), nullable=False, comment='业务唯一标识（建议使用 svc:IP:PORT:PROTOCOL）'),
    sa.Column('service_name', sa.String(length=100), nullable=True, comment='服务名称（如 http、ssh、mysql）'),
    sa.Column('port', sa.Integer(), nullable=False, comment='端口号（1-65535）'),
    sa.Column('protocol', sa.String(length=10), nullable=False, comment='协议类型（TCP/UDP）'),
    sa.Column('product', sa.String(length=255), nullable=True, comment='产品名称（如 Apache、Nginx、MySQL）'),
    sa.Column('version', sa.String(length=100), nullable=True, comment='版本号'),
    sa.Column('banner', sa.Text(), nullable=True, comment='Banner信息'),
    sa.Column('is_http', sa.Boolean(), nullable=False, comment='是否为HTTP/HTTPS服务'),
    sa.Column('risk_score', sa.Float(), nullable=False, comment='风险评分（0-10）'),
    sa.Column('asset_category', sa.String(length=50), nullable=True, comment='资产分类（WEB/DATABASE/MIDDLEWARE/CACHE/MESSAGE_QUEUE等）'),
    sa.Column('scope_policy', sa.String(length=50), nullable=False, comment='范围策略（IN_SCOPE/OUT_OF_SCOPE）'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='元数据（JSONB格式，包含cpe、scripts结果等）'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间戳'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间戳'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间戳'),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='创建者标识'),
    sa.CheckConstraint("protocol IN ('TCP', 'UDP')", name=op.f('ck_assets_service_chk_service_protocol')),
    sa.CheckConstraint('port >= 1 AND port <= 65535', name=op.f('ck_assets_service_chk_service_port')),
    sa.CheckConstraint('risk_score >= 0 AND risk_score <= 10', name=op.f('ck_assets_service_chk_service_risk_score')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets_service')),
    comment='服务资产表'
    )
    op.create_index(op.f('ix_assets_service_asset_category'), 'assets_service', ['asset_category'], unique=False)
    op.create_index(op.f('ix_assets_service_created_at'), 'assets_service', ['created_at'], unique=False)
    op.create_index(op.f('ix_assets_service_external_id'), 'assets_service', ['external_id'], unique=True)
    op.create_index(op.f('ix_assets_service_is_deleted'), 'assets_service', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_assets_service_is_http'), 'assets_service', ['is_http'], unique=False)
    op.create_index(op.f('ix_assets_service_port'), 'assets_service', ['port'], unique=False)
    op.create_index(op.f('ix_assets_service_product'), 'assets_service', ['product'], unique=False)
    op.create_index(op.f('ix_assets_service_protocol'), 'assets_service', ['protocol'], unique=False)
    op.create_index(op.f('ix_assets_service_scope_policy'), 'assets_service', ['scope_policy'], unique=False)
    op.create_index(op.f('ix_assets_service_service_name'), 'assets_service', ['service_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assets_service_service_name'), table_name='assets_service')
    op.drop_index(op.f('ix_assets_service_scope_policy'), table_name='assets_service')
    op.drop_index(op.f('ix_assets_service_protocol'), table_name='assets_service')
    op.drop_index(op.f('ix_assets_service_product'), table_name='assets_service')
    op.drop_index(op.f('ix_assets_service_port'), table_name='assets_service')
    op.drop_index(op.f('ix_assets_service_is_http'), table_name='assets_service')
    op.drop_index(op.f('ix_assets_service_is_deleted'), table_name='assets_service')
    op.drop_index(op.f('ix_assets_service_external_id'), table_name='assets_service')
    op.drop_index(op.f('ix_assets_service_created_at'), table_name='assets_service')
    op.drop_index(op.f('ix_assets_service_asset_category'), table_name='assets_service')
    op.drop_table('assets_service')
    op.drop_index(op.f('ix_assets_relationship_target_type'), table_name='assets_relationship')
    op.drop_index(op.f('ix_assets_relationship_target_external_id'), table_name='assets_relationship')
    op.drop_index(op.f('ix_assets_relationship_source_type'), table_name='assets_relationship')
    op.drop_index(op.f('ix_assets_relationship_source_external_id'), table_name='assets_relationship')
    op.drop_index(op.f('ix_assets_relationship_relation_type'), table_name='assets_relationship')
    op.drop_index(op.f('ix_assets_relationship_is_deleted'), table_name='assets_relationship')
    op.drop_index(op.f('ix_assets_relationship_created_at'), table_name='assets_relationship')
    op.drop_table('assets_relationship')
    op.drop_index(op.f('ix_assets_organization_scope_policy'), table_name='assets_organization')
    op.drop_index(op.f('ix_assets_organization_name'), table_name='assets_organization')
    op.drop_index(op.f('ix_assets_organization_is_primary'), table_name='assets_organization')
    op.drop_index(op.f('ix_assets_organization_is_deleted'), table_name='assets_organization')
    op.drop_index(op.f('ix_assets_organization_external_id'), table_name='assets_organization')
    op.drop_index(op.f('ix_assets_organization_credit_code'), table_name='assets_organization')
    op.drop_index(op.f('ix_assets_organization_created_at'), table_name='assets_organization')
    op.drop_table('assets_organization')
    op.drop_index(op.f('ix_assets_netblock_scope_policy'), table_name='assets_netblock')
    op.drop_index(op.f('ix_assets_netblock_is_internal'), table_name='assets_netblock')
    op.drop_index(op.f('ix_assets_netblock_is_deleted'), table_name='assets_netblock')
    op.drop_index(op.f('ix_assets_netblock_external_id'), table_name='assets_netblock')
    op.drop_index(op.f('ix_assets_netblock_created_at'), table_name='assets_netblock')
    op.drop_index(op.f('ix_assets_netblock_cidr'), table_name='assets_netblock')
    op.drop_index(op.f('ix_assets_netblock_asn_number'), table_name='assets_netblock')
    op.drop_table('assets_netblock')
    op.drop_index(op.f('ix_assets_ip_version'), table_name='assets_ip')
    op.drop_index(op.f('ix_assets_ip_scope_policy'), table_name='assets_ip')
    op.drop_index(op.f('ix_assets_ip_is_deleted'), table_name='assets_ip')
    op.drop_index(op.f('ix_assets_ip_is_cloud'), table_name='assets_ip')
    op.drop_index(op.f('ix_assets_ip_external_id'), table_name='assets_ip')
    op.drop_index(op.f('ix_assets_ip_created_at'), table_name='assets_ip')
    op.drop_index(op.f('ix_assets_ip_country_code'), table_name='assets_ip')
    op.drop_index(op.f('ix_assets_ip_asn_number'), table_name='assets_ip')
    op.drop_table('assets_ip')
    op.drop_index(op.f('ix_assets_domain_scope_policy'), table_name='assets_domain')
    op.drop_index(op.f('ix_assets_domain_root_domain'), table_name='assets_domain')
    op.drop_index(op.f('ix_assets_domain_name'), table_name='assets_domain')
    op.drop_index(op.f('ix_assets_domain_is_resolved'), table_name='assets_domain')
    op.drop_index(op.f('ix_assets_domain_is_deleted'), table_name='assets_domain')
    op.drop_index(op.f('ix_assets_domain_external_id'), table_name='assets_domain')
    op.drop_index(op.f('ix_assets_domain_created_at'), table_name='assets_domain')
    op.drop_table('assets_domain')
    op.drop_index(op.f('ix_assets_credential_validation_result'), table_name='assets_credential')
    op.drop_index(op.f('ix_assets_credential_username'), table_name='assets_credential')
    op.drop_index(op.f('ix_assets_credential_scope_policy'), table_name='assets_credential')
    op.drop_index(op.f('ix_assets_credential_provider'), table_name='assets_credential')
    op.drop_index(op.f('ix_assets_credential_is_deleted'), table_name='assets_credential')
    op.drop_index(op.f('ix_assets_credential_external_id'), table_name='assets_credential')
    op.drop_index(op.f('ix_assets_credential_email'), table_name='assets_credential')
    op.drop_index(op.f('ix_assets_credential_cred_type'), table_name='assets_credential')
    op.drop_index(op.f('ix_assets_credential_created_at'), table_name='assets_credential')
    op.drop_table('assets_credential')
    op.drop_index(op.f('ix_assets_client_application_scope_policy'), table_name='assets_client_application')
    op.drop_index(op.f('ix_assets_client_application_platform'), table_name='assets_client_application')
    op.drop_index(op.f('ix_assets_client_application_package_name'), table_name='assets_client_application')
    op.drop_index(op.f('ix_assets_client_application_is_deleted'), table_name='assets_client_application')
    op.drop_index(op.f('ix_assets_client_application_external_id'), table_name='assets_client_application')
    op.drop_index(op.f('ix_assets_client_application_created_at'), table_name='assets_client_application')
    op.drop_index(op.f('ix_assets_client_application_app_name'), table_name='assets_client_application')
    op.drop_table('assets_client_application')
    op.drop_index(op.f('ix_assets_certificate_subject_cn'), table_name='assets_certificate')
    op.drop_index(op.f('ix_assets_certificate_scope_policy'), table_name='assets_certificate')
    op.drop_index(op.f('ix_assets_certificate_issuer_cn'), table_name='assets_certificate')
    op.drop_index(op.f('ix_assets_certificate_is_self_signed'), table_name='assets_certificate')
    op.drop_index(op.f('ix_assets_certificate_is_revoked'), table_name='assets_certificate')
    op.drop_index(op.f('ix_assets_certificate_is_expired'), table_name='assets_certificate')
    op.drop_index(op.f('ix_assets_certificate_is_deleted'), table_name='assets_certificate')
    op.drop_index(op.f('ix_assets_certificate_external_id'), table_name='assets_certificate')
    op.drop_index(op.f('ix_assets_certificate_created_at'), table_name='assets_certificate')
    op.drop_table('assets_certificate')
    # ### end Alembic commands ###
