"""add_aux_tables

Revision ID: 408a997e888f
Revises: 1374ac1ba77b
Create Date: 2026-01-20 09:46:32.750898

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '408a997e888f'
down_revision = '1374ac1ba77b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_logs',
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID primary key'),
    sa.Column('filename', sa.String(length=500), nullable=False, comment='Source file name'),
    sa.Column('file_size', sa.BigInteger(), nullable=True, comment='File size in bytes'),
    sa.Column('file_hash', sa.String(length=64), nullable=True, comment='File hash'),
    sa.Column('file_path', sa.Text(), nullable=True, comment='Stored file path'),
    sa.Column('format', sa.String(length=50), nullable=False, comment='File format'),
    sa.Column('parser_version', sa.String(length=20), nullable=True, comment='Parser version'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Import status'),
    sa.Column('progress', sa.Integer(), nullable=False, comment='Progress percentage'),
    sa.Column('records_total', sa.Integer(), nullable=False, comment='Total records'),
    sa.Column('records_success', sa.Integer(), nullable=False, comment='Successful records'),
    sa.Column('records_failed', sa.Integer(), nullable=False, comment='Failed records'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error summary'),
    sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Error details'),
    sa.Column('assets_created', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Created assets summary'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update timestamp'),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='Creator identifier'),
    sa.Column('duration_seconds', sa.Integer(), nullable=True, comment='Duration in seconds'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_logs'))
    )
    op.create_index(op.f('ix_import_logs_created_at'), 'import_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_import_logs_created_by'), 'import_logs', ['created_by'], unique=False)
    op.create_index(op.f('ix_import_logs_format'), 'import_logs', ['format'], unique=False)
    op.create_index(op.f('ix_import_logs_status'), 'import_logs', ['status'], unique=False)
    op.create_table('operation_logs',
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID primary key'),
    sa.Column('operation_type', sa.String(length=50), nullable=False, comment='Operation type'),
    sa.Column('entity_type', sa.String(length=50), nullable=False, comment='Entity type'),
    sa.Column('entity_id', sa.String(length=255), nullable=True, comment='Entity identifier'),
    sa.Column('operation_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Operation detail'),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Previous value'),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='New value'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp'),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='Creator identifier'),
    sa.Column('ip_address', postgresql.INET(), nullable=True, comment='Client IP address'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='User agent'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operation_logs'))
    )
    op.create_index(op.f('ix_operation_logs_created_at'), 'operation_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_operation_logs_created_by'), 'operation_logs', ['created_by'], unique=False)
    op.create_index(op.f('ix_operation_logs_entity_id'), 'operation_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_operation_logs_entity_type'), 'operation_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_operation_logs_operation_type'), 'operation_logs', ['operation_type'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID primary key'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Tag name'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='Tag category'),
    sa.Column('color', sa.String(length=20), nullable=True, comment='Display color'),
    sa.Column('description', sa.Text(), nullable=True, comment='Description'),
    sa.Column('usage_count', sa.Integer(), nullable=False, comment='Usage count'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update timestamp'),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='Creator identifier'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags'))
    )
    op.create_index(op.f('ix_tags_category'), 'tags', ['category'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('asset_tags',
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID primary key'),
    sa.Column('asset_type', sa.String(length=50), nullable=False, comment='Asset type'),
    sa.Column('asset_id', sa.String(length=255), nullable=False, comment='Asset identifier'),
    sa.Column('tag_id', sa.UUID(), nullable=False, comment='Tag identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp'),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='Creator identifier'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_asset_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_tags')),
    sa.UniqueConstraint('asset_type', 'asset_id', 'tag_id', name='uq_asset_tag'),
    comment='Asset tags'
    )
    op.create_index('ix_asset_tags_asset_type_asset_id', 'asset_tags', ['asset_type', 'asset_id'], unique=False)
    op.create_index('ix_asset_tags_created_at', 'asset_tags', ['created_at'], unique=False)
    op.create_index('ix_asset_tags_tag_id', 'asset_tags', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_asset_tags_tag_id', table_name='asset_tags')
    op.drop_index('ix_asset_tags_created_at', table_name='asset_tags')
    op.drop_index('ix_asset_tags_asset_type_asset_id', table_name='asset_tags')
    op.drop_table('asset_tags')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_category'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_operation_logs_operation_type'), table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_entity_type'), table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_entity_id'), table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_created_by'), table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_created_at'), table_name='operation_logs')
    op.drop_table('operation_logs')
    op.drop_index(op.f('ix_import_logs_status'), table_name='import_logs')
    op.drop_index(op.f('ix_import_logs_format'), table_name='import_logs')
    op.drop_index(op.f('ix_import_logs_created_by'), table_name='import_logs')
    op.drop_index(op.f('ix_import_logs_created_at'), table_name='import_logs')
    op.drop_table('import_logs')
    # ### end Alembic commands ###
